language: python

os:
    - linux
    - osx

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install mock; fi
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip --quiet install mock; fi

install:
    - python setup.py install

script:
    - nosetests

matrix:
    allow_failures:
        - python: "2.7"
        - python: "3.4"
