language: python

os:
    - linux

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "pypy"

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip --quiet install mock; fi

install:
    - python setup.py install

script:
    - nosetests
